### ISSUE TITLE
supporting python functions returning tuples would be _very_ useful

### ISSUE THREAD

**Issue by UnixJunkie** [mooreryan/ocaml_python_bindgen#1]
in the *_specs.txt file.
At first, maybe supporting only tuples where all elements are of the same type would be nice.

For example, support:
```ocaml
int * int
int * int * int
```
up to the same arity pyml supports.
I needed to wrap a Python class where the returned values are:
(int * int * int * int * int) list
and
(int * int * int) list

**Comment by mooreryan** [comment]
Hey so what kind of function are you wrapping...could you put a little example?  

And assuming that the python function returns an actual python tuple...how you would like to use it from the OCaml side?  Converting tuples into something usable from the OCaml side is flexible in pyml...you can treat them as OCaml tuples, or lists, or arrays, or even as an abstract type, so I'm curious how you would like to use it.  

Also, would it be mainly returning tuples, or letting tuples be parameters for functions as well?

Currently I deal with tuples like [this](https://mooreryan.github.io/ocaml_python_bindgen/tuples/) or sometimes like [this](https://mooreryan.github.io/ocaml_python_bindgen/dictionaries-2/) if you need functors.  But I could see how a more "natural" support for tuples would be helpful...it's just a matter of finding a pleasant way to deal with them.

**Comment by UnixJunkie** [comment]
The functions were like these:
```ocaml
# assert(get_distances(m) == [(0, 1, 1),
#                             (0, 2, 2),
#                             (0, 3, 3),
#                             (0, 4, 2),
#                             (0, 5, 1),
#                             (1, 2, 1),
#                             (1, 3, 2),
#                             (1, 4, 3),
#                             (1, 5, 2),
#                             (2, 3, 1),
#                             (2, 4, 2),
#                             (2, 5, 3),
#                             (3, 4, 1),
#                             (3, 5, 2),
#                             (4, 5, 1)])
# assert(type_atoms(m) == [(6, 2, 1, 3, 0),
#                          (6, 2, 1, 3, 0),
#                          (6, 2, 1, 3, 0),
#                          (6, 2, 1, 3, 0),
#                          (6, 2, 1, 3, 0),
#                          (6, 2, 1, 3, 0)])
```

I was just looking for returning tuples, and the tuple values were all of the same type (int, in this example).
I think python tuples should be mapped to ocaml tuples by default (maybe some users will want
to translate them to list/array, but I feel this should not be the default).

**Comment by UnixJunkie** [comment]
Supporting all the ocaml types (and their python equivalent) would be nice: int, char, float, bool, string.

**Comment by mooreryan** [comment]
Okay, I see now...yeah I've hacked together some basic tuple support, but not yet tuples within lists/arrays/seqs.  I will play around with it some more and see if there is any weirdness when dealing with them in general.

**Comment by UnixJunkie** [comment]
I would really love to have tuples being supported, at least as return type of python functions.
They should be mapped to an ocaml tuple (type: 'a * 'b * 'c).
Of course, in the interface, we would fix those type variables to some concrete type (possibly any basic OCaml type: int, float, char, string, whatever).

**Comment by UnixJunkie** [comment]
As a kind of sponsorship, I can send you my copy of the book moneyball, if that interests you. :)

**Comment by mooreryan** [comment]
Haha, I do love moneyball.  Anyway, tuple support is finally here, and in [version 0.3.0](https://github.com/mooreryan/ocaml_python_bindgen/blob/main/CHANGELOG.md#030-2022-03-18)!  You can see some examples of usage [here](https://github.com/mooreryan/ocaml_python_bindgen/tree/main/examples/tuples).

(Currently not on opam yet, but you could pin it.)

Let me know if this works for you!

**Comment by UnixJunkie** [comment]
Ok, I will test and let you know.

**Comment by UnixJunkie** [comment]
I hereby confirm that a hacker (@mooreryan) killed this feature request.
