### ISSUE TITLE
pyml_bindgen invocation example in case there is no class [question]

### ISSUE THREAD

**Issue by UnixJunkie** [mooreryan/ocaml_python_bindgen#8]
Do you have a command-line example in case you generate bindings for a python
file with a single function inside, no class defined?

**Comment by mooreryan** [comment]
This example has just functions in a module with no class: https://github.com/mooreryan/ocaml_python_bindgen/tree/main/examples/importing_modules.  `pyml_bindgen` is invoked through a dune rule, but you will get the idea.

Also, this cram test has an example of binding functions that are just associated with a module and not a class: https://github.com/mooreryan/ocaml_python_bindgen/blob/main/test/module_function_binding.t/run.t.

Let me know if this helps.

**Comment by UnixJunkie** [comment]
Ok, so we have to put NA when there is no Python class.
With those examples, I should be able to make what I need.

**Comment by mooreryan** [comment]
Technically you can put any string in there...I just use `NA` because it's clearer.  Originally you could only bind class associated methods, then I changed it, but haven't gotten around to fixing the command line option yet....it's on my to do list.

**Comment by mooreryan** [comment]
Feel free to reopen if you have additional questions, but for now I will close this.
