### ISSUE TITLE
there are many depends in the opam file

### ISSUE THREAD

**Issue by UnixJunkie** [mooreryan/ocaml_python_bindgen#9]
I don't know if you can or even should do something about it.
But, it makes the install quite slow; also, I suspect the install will break easily in the future, or be incompatible with what the user already have installed.

**Comment by mooreryan** [comment]
Yeah there are some pretty heavy deps in there.  For example, I just did a little experiment and found that removing just `re2` and `ppx_string` would get the `ocaml install .` command in a fresh switch down from 67 to 21 dependencies.

I have been meaning to switch Re2 to `ocaml-re` for a while now, but haven't gotten around to it.  The `ppx_string` one is easier to remove, but removing that one but not `re2` doesn't really help according to the opam solver.

**Comment by UnixJunkie** [comment]
For regexps, there is also the Str module.
I don't know what people have against it; it always solves my problems once I have a correct regexp.

**Comment by mooreryan** [comment]
On the `v0.3.0` branch the `opam install .` command from the repository on a fresh switch wants to install 72 packages.  The same command on the current `dev` branch which will be 0.3.1 only wants 30 (eg switching re2 to re, and no core, core_bench, or bisect_ppx).  Much faster install time too.

At some time I may remove `ppx_string`, but for now it will stay as it is used in quite a few places currently.

**Comment by UnixJunkie** [comment]
that's a lot better already

**Comment by mooreryan** [comment]
I will close this for now.  The only other dep that would be "easy" to remove is ppx_string and its used quite a lot.
